
services:
  backend:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tp3_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  aerich:
    build:
      context: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    entrypoint: ["aerich"]

volumes:
  postgres_data:
